{"name": "test_update_user_invalid", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://cf-automation-airline-api.onrender.com/users/USER_INVALID_ID", "trace": "auth_headers = {'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c3ItOWQxNWUyNzIiLCJyb2xlIjoiYWRtaW4ifQ.zqxWBnG-pflzUMiSznhGyZodzP9gJtpp3yHroB18YjU', 'Content-Type': 'application/json'}\n\n    def test_update_user_invalid(auth_headers):\n>       response = api_request(\"PUT\", f\"{BASE_URL}{USERS}/USER_INVALID_ID\", json={\"email\": \"fail@example.com\"}, headers=auth_headers)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nairport_api_test/test/users/test_user.py:63: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nvenv/lib/python3.11/site-packages/tenacity/__init__.py:338: in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\nvenv/lib/python3.11/site-packages/tenacity/__init__.py:477: in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nvenv/lib/python3.11/site-packages/tenacity/__init__.py:378: in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\nvenv/lib/python3.11/site-packages/tenacity/__init__.py:420: in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\nvenv/lib/python3.11/site-packages/tenacity/__init__.py:187: in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n/usr/lib/python3.11/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n/usr/lib/python3.11/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\nvenv/lib/python3.11/site-packages/tenacity/__init__.py:480: in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\nairport_api_test/utils/api_helpers.py:8: in api_request\n    try:\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Response [422]>\n\n    def raise_for_status(self):\n        \"\"\"Raises :class:`HTTPError`, if one occurred.\"\"\"\n    \n        http_error_msg = \"\"\n        if isinstance(self.reason, bytes):\n            # We attempt to decode utf-8 first because some servers\n            # choose to localize their reason strings. If the string\n            # isn't utf-8, we fall back to iso-8859-1 for all other\n            # encodings. (See PR #3538)\n            try:\n                reason = self.reason.decode(\"utf-8\")\n            except UnicodeDecodeError:\n                reason = self.reason.decode(\"iso-8859-1\")\n        else:\n            reason = self.reason\n    \n        if 400 <= self.status_code < 500:\n            http_error_msg = (\n                f\"{self.status_code} Client Error: {reason} for url: {self.url}\"\n            )\n    \n        elif 500 <= self.status_code < 600:\n            http_error_msg = (\n                f\"{self.status_code} Server Error: {reason} for url: {self.url}\"\n            )\n    \n        if http_error_msg:\n>           raise HTTPError(http_error_msg, response=self)\nE           requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://cf-automation-airline-api.onrender.com/users/USER_INVALID_ID\n\nvenv/lib/python3.11/site-packages/requests/models.py:1026: HTTPError"}, "attachments": [{"name": "stdout", "source": "00c3ac0a-fa56-4502-aa1c-31979c5ad93e-attachment.txt", "type": "text/plain"}], "start": 1757698539656, "stop": 1757698544868, "uuid": "98286926-5b84-4af8-a8ef-d832d7b16fd3", "historyId": "a61f3ed158c1171a49f6809c2c9b1da9", "testCaseId": "a61f3ed158c1171a49f6809c2c9b1da9", "fullName": "airport_api_test.test.users.test_user#test_update_user_invalid", "labels": [{"name": "parentSuite", "value": "airport_api_test.test.users"}, {"name": "suite", "value": "test_user"}, {"name": "host", "value": "LUIS-RODRIGUEZ-N23"}, {"name": "thread", "value": "2730779-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "airport_api_test.test.users.test_user"}], "titlePath": ["airport_api_test", "test", "users", "test_user.py"]}